#-------------------------------
# General Site Settings

title: Developer KISIK
logo: 
author: themefisher
description: this is meta description
email: wis1906@naver.com
phone: 010 9747 2355
address: Incheon Korea
copyright: Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Getjekyllthemes](https://getjekyllthemes.com)

menu:
- {name: About, link: '/about'}
- {name: Blog, link: '/blog'}
- {name: Portfolio, link: '/portfolio'}
- {name: Contact, link: '/contact'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: "반갑습니다! <br> <strong>상상</strong>을 <strong>요리</strong>하는 개발자 <br> <strong>김기식</strong>입니다."

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  안녕하세요.

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Research and Plan"
    icon : "assets/images/icons/plan.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Design and Develop"
    icon : "assets/images/icons/design.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
    
  - title : "Deliver"
    icon : "assets/images/icons/print.png"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."


# My Team Section
team:
  - title : "Jack Schenziwe"
    image : "assets/images/team/member-1.png"
    designation : "Project Manager"
    
  - title : "Julias Carlie"
    image : "assets/images/team/member-2.png"
    designation : "Web Developer"
    
  - title : "John Doe"
    image : "assets/images/team/member-3.png"
    designation : "Designer"


#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: Unity Engine, color: '#4169e1', value: '90%'}
- {name: Unreal Engine, color: '#39383f', value: '60%'}
- {name: C++, color: '#98f375', value: '80%'}
- {name: C, color: '#efef51', value: '70%'}
- {name: C Sharp, color: '#6f11f6', value: '60%'}
- {name: JAVA, color: '#f69c11', value: '40%'}
- {name: Python, color: '#f75e80', value: '40%'}
- {name: Little Design Skills, color: '#7520ff', value: '70%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: 게임 개발 협업, icon: 'icon-1.png', date: '2020.07 - 2021.12', organization: 'Funnyeve',
detail: '인지도가 높은 캐릭터를 보유한 회사 `퍼니이브`와 협업 계약을 맺고 모바일게임 공동 개발을 수행하였습니다. 저는 `기획, 프로그래밍` 업무를 담당하였고, 회사는 `기획, 디자인, 유통` 업무를 담당하였습니다. 게임 속 모든 프로그램 코드는 제가 직접 설계하였습니다. 기획은 공동으로 담당하여서 진행하였으며, 디자인의 경우 일부만 제가 수행하고, 대부분은 회사에서 담담하였습니다.'}
- {name: Task Force Team & UI Designer, icon: 'icon-2.png', date: '2020.10 - 2021.12', organization: '인천광역시 교육청 사이버 진로 교육원',
detail: '2020년 인천광역시 교육청 사이버진로교육원에 T/F 팀 위원으로 초청되었습니다. 그동안 개발했던 게임 이력을 토대로 스카웃되었습니다. 당시 `체험형 게임 개발 분과`로 배정받아, 게임 개발의 전문 지식을 바탕으로 수행하는 업무들을 담당하였습니다. 주 업무는, 중고등학생들이 COVID-19 상황에서도 학생 중심의 디지털 게임 공간에서 가상의 회사를 만들고, 각자의 직무를 수행하며 본인의 진로를 찾아가는 게임을 설계하는 과정에 기여하였습니다. 총 2가지 게임을 설계하였습니다. \n [파이퓨처컴퍼니 My Future Company] 가상의 회사에서 각자의 직무에 맞는 문제 상황을 해결하며 역할을 체험하는 게임(모바일). \n[마이리얼커리어 My Real Career] 현실과 가상이 결합한 실감형 콘텐츠를 활용하여 직업 현장을 생생하게 체험하는 게임(VR, HMD).'}
- {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: <strong>공학 학사</strong>, date: '2015.03 - 2020.02', organization: '인천대학교 임베디드시스템공학과'}
- {name: <strong>공학 석사</strong>, date: '2020.03 - Ing', organization: '인천대학교 컴퓨터공학과'}

#-------------------------------
# Awards Section

award-title: Awards
award:
- {name: <strong>우수논문상</strong>, date: '2021', organization: '한국게임학회',
detail: '`실내 구면 파노라마에서의 볼륨 검출을 통한 AR 게임 공간 구성`에 대한 논문으로 2021년도 한국게임학회 춘계학술발표대회에서 우수논문상 수상'}
- {name: <strong>인천대를 빛낸 인천대 학생 표창장</strong>, date: '2020', organization: '인천대학교',
detail: '다회의 논문 개제와 논문상 수상 실적을 인정받아 인천대를 대표하는 학생으로 선별되어 표창장 수상'}
- {name: <strong>우수논문상</strong>, date: '2020', organization: '한국정보처리학회',
detail: '`구면 PTAM의 구현을 위한 카메라 모델 설계`에 대한 논문으로 2020년도 한국정보처리학회 춘계학술발표대회에서 우수논문상 수상'}
- {name: <strong>우수논문상</strong>, date: '2020', organization: '한국게임학회',
detail: '`게임 엔진에서의 구면 파노라마 비디오 생성 기법`에 대한 논문으로 2020년도 한국게임학회 춘계학술발표대회에서 우수논문상 수상'}
- {name: <strong>우수논문발표상</strong>, date: '2020', organization: '한국게임학회',
detail: '`구면 파노라마 배경의 FPS 게임에서의 질감을 고려한 효과음 생성`에 대한 논문으로 2020년도 한국게임학회 추계학술발표대회에서 우수발표상 수상'}
- {name: <strong>INU 창의적 캡스톤디자인 경진대회 입상</strong>, date: '2019', organization: '인천대학교',
detail: '`향상된 SLAM 기능을 가진 특정 개체 추적 로봇`을 설계하여 제 15회 인천대학교 창의적종합설계경진대회에서 동상 수상'}
- {name: <strong>우수논문발표상</strong>, date: '2019', organization: '한국게임학회',
detail: '`바닷속 세계 RPG의 스토리 설계`에 대한 논문으로 2019년도 한국게임학회 춘계학술발표대회에서 우수발표상(넥슨코리아상) 수상함'}
- {name: <strong>INU 창의적 캡스톤디자인 경진대회 입상</strong>, date: '2017', organization: '인천대학교',
detail: '`센서식 자동 문 고정장치`를 설계하여 제 12회 인천대학교 창의적종합설계경진대회에서 동상 수상'}
- {name: <strong>창의적종합설계경진대회 </strong>, date: '2016', organization: '인천대학교',
detail: '`보이지 않는 신디사이저`를 설계하여 제 12회 인천대학교 창의적종합설계경진대회에서 은상 수상'}


#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: UI Design,
    icon: ti-palette,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: # Add true to select section
  }
- {
    name: UX Design,
    icon: ti-vector,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: true # Add true to select section
  }
- {
    name: Interaction Design,
    icon: ti-panel,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "UI/UX Design",
    type : "design"
  }
- {
    title : "BRANDING",
    type : "branding"
  }
- {
    title : "ILLUSTRATION",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation : "CEO, Funder"
    content : "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."
    
  - name: "Jesica Gomez"
    image: "assets/images/testimonial/client-1.png"
    designation: "CEO, Funder"
    content: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, <strong>quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</strong> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: wis1906@naver.com
